name: sol_parser
description: >
  Recursive-descent Solidity parser for the sol_pkgs compiler.
  Converts a token stream into a typed AST.
version: 0.1.1
repository: https://github.com/normidar/sol_pkgs/tree/main/packages/sol_parser

environment:
  sdk: ">=3.12.0 <4.0.0"

dependencies:
  sol_support: ^0.1.0+1
  sol_lexer: ^0.1.0+1
  sol_ast: ^0.1.0+2

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.0
